create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

drop policy if exists "Allow public contact submissions"
on public.contact_submissions;

create policy "Allow public contact submissions"
on public.contact_submissions
for insert
to anon
with check (true);

drop policy if exists "Allow public submission reading"
on public.contact_submissions;

create policy "Allow public submission reading"
on public.contact_submissions
for select
to anon
using (true);
